### PR TITLE
Upgrade vulnerable bl library

### PR DESCRIPTION
**Pull request by mhessoct**

### CODE REVIEW

**Comment by mhessoct** [comment]
@trevorlinton let me know if I should have someone else look at this

**Review by ketiko — APPROVED** [review]
I'm not familiar with this at all but it seems fine to me. You requested my review so I'll approve but defer to others that have been requested also.

Make sure to create another GitHub release after. It looks like we've been creating them for past versions and it would be good to keep that up.

**Comment by ketiko** [comment]
Should we enable the GitHub security scans on this repo? https://github.com/octanner/msgpack5/settings/security_analysis

**Comment by ketiko** [comment]
We also don't have any branch protections setup in GH, like to require pull request approvals. And we don't have any of the team permissions setup to control who can do what.

FYI this is also a public repository.

**Comment by mhessoct** [comment]
@ketiko 
We're missing a lot of the checks I would've expected on an OCT repo. As far as I can tell, this library is actively used in classic CA/YB prod, so setting up all the protections seems important. 

I'm not really sure which team is responsible for this repo, so I added a few people that I thought might have some good input. Thanks for looking at it Ryan!

**Review by trevorlinton — APPROVED** [review]

**Pull request merged**
